### ISSUE TITLE
com.getkeepsafe.relinker.MissingLibraryException: lib/armeabi/libepic.so

### ISSUE THREAD

**Issue by ghost** [android-hacker/VAExposed#783] opened 2019-12-21 17:44 UTC
**Describe the bug**
Any apps installed in Virtual Xposed gets stuck in Opening screen

**To Reproduce**
1. Install VirtualXposed_0.18.0_for_GameGuardian.apk
2. Open Virtual Xposed
3. Open Xposed installer or any installed apps 

**Expected behavior**
Be able to run any app installed in Virtual Xposed

**Screenshots**
![image](https://user-images.githubusercontent.com/24647715/71311683-7691aa80-2421-11ea-8504-1bd75444e2e4.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Opera 
 - Version: 65.0.3467.78

**Smartphone (please complete the following information):**
 - Device: Bluestacks 4
 - OS: Android 7.1.1
 - Browser: Stock browser
 - Version: 5.150.10.4006

**Additional context**
I wanted to hide GG in Virtual Xposed so that some games doesn't detect GG. I can then open GG and use root access in virtual to hack apps outside virtual
See: https://gameguardian.net/forum/gallery/image/581-avoid-detection-root-from-virtual-space-virtualxposed-gameguardian/?browse=1

Other emulator have same problem but I like Bluestacks better because games doesn't detect emulator

This logcat constantly repeating over and over when the bug occur: 
```
12-21 17:38:19.511 I/ActivityManager(1921): Start proc 6807:io.va.exposed:p0/u0a68 for activity io.va.exposed/com.lody.virtual.client.stub.StubActivity$C0
12-21 17:38:19.520 D/WindowManager(1921): in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true
12-21 17:38:19.607 W/MethodInvocationStub(6807): Unable to build HookDelegate: BinderInvocationStub.
12-21 17:38:19.616 W/MethodInvocationStub(6807): Unable to build HookDelegate: BinderInvocationStub.
12-21 17:38:19.643 I/CrashlyticsCore(6807): Initializing Crashlytics 2.6.0.22
12-21 17:38:19.670 I/VClientImpl(6807): Binding application com.crfhvkrpkbs.jm.epjhj, (com.crfhvkrpkbs.jm.epjhj)
12-21 17:38:19.681 D/NativeEngine(6807): DexOrJarPath = /data/user/0/io.va.exposed/virtual/data/app/com.crfhvkrpkbs.jm.epjhj/base.apk, OutputPath = null.
12-21 17:38:19.684 D/NativeEngine(6807): DexOrJarPath = /data/user/0/io.va.exposed/virtual/data/app/com.crfhvkrpkbs.jm.epjhj/base.apk, OutputPath = null.
12-21 17:38:19.687 D/ApplicationLoaders(6807): ignored Vulkan layer search path /data/user/0/io.va.exposed/virtual/data/app/com.crfhvkrpkbs.jm.epjhj/lib:/system/fake-libs:/data/user/0/io.va.exposed/virtual/data/app/com.crfhvkrpkbs.jm.epjhj/base.apk!/lib/x86:/data/user/0/io.va.exposed/virtual/data/app/com.crfhvkrpkbs.jm.epjhj/base.apk!/lib/x86 for namespace 0xf57b2090
12-21 17:38:19.687 W/art     (6807): JIT profile information will not be recorded: profile file does not exits.
12-21 17:38:19.690 I/VClientImpl(6807): Xposed is enabled.
12-21 17:38:19.693 D/AndroidRuntime(6807): Shutting down VM
12-21 17:38:19.696 I/XApp    (6807): uncaught :Thread[main,5,main]
12-21 17:38:19.696 I/XApp    (6807): com.getkeepsafe.relinker.MissingLibraryException: lib/armeabi/libepic.so
12-21 17:38:19.696 I/XApp    (6807): 	at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:85)
12-21 17:38:19.696 I/XApp    (6807): 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
12-21 17:38:19.696 I/XApp    (6807): 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
12-21 17:38:19.696 I/XApp    (6807): 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
12-21 17:38:19.696 I/XApp    (6807): 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
12-21 17:38:19.696 I/XApp    (6807): 	at me.weishu.exposed.ExposedBridge.initOnce(ExposedBridge.java:115)
12-21 17:38:19.696 I/XApp    (6807): 	at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:337)
12-21 17:38:19.696 I/XApp    (6807): 	at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:218)
12-21 17:38:19.696 I/XApp    (6807): 	at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:213)
12-21 17:38:19.696 I/XApp    (6807): 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:124)
12-21 17:38:19.696 I/XApp    (6807): 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:77)
12-21 17:38:19.696 I/XApp    (6807): 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-21 17:38:19.696 I/XApp    (6807): 	at android.os.Looper.loop(Looper.java:154)
12-21 17:38:19.696 I/XApp    (6807): 	at android.app.ActivityThread.main(ActivityThread.java:6125)
12-21 17:38:19.696 I/XApp    (6807): 	at java.lang.reflect.Method.invoke(Native Method)
12-21 17:38:19.696 I/XApp    (6807): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
12-21 17:38:19.696 I/XApp    (6807): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
12-21 17:38:19.708 I/art     (6807): System.exit called, status: 0
12-21 17:38:19.708 I/AndroidRuntime(6807): VM exiting with result code 0, cleanup skipped.
12-21 17:38:19.749 I/ActivityManager(1921): Process io.va.exposed:p0 (pid 6807) has died
12-21 17:38:19.749 D/ActivityManager(1921): cleanUpApplicationRecord -- 6807
12-21 17:38:19.750 D/ActivityManager(1921): TopActivityInfo, pkgName: io.va.exposed activityName: io.va.exposed/com.lody.virtual.client.stub.StubActivity$C0 callingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
12-21 17:38:19.750 D/ActivityManager(1921): Sending app launch intent for appName: VirtualXposed pkgName: io.va.exposed
12-21 17:38:19.751 D/ActivityManager(1921): Sending TopActivity Info
12-21 17:38:19.755 W/Zygote  (6843): Third party app and access not allowed io.va.exposed:p0
12-21 17:38:19.759 I/art     (6843): Late-enabling -Xcheck:jni
12-21 17:38:19.759 W/art     (6843): Unexpected CPU variant for X86 using defaults: x86
12-21 17:38:19.761 I/ActivityManager(1921): Start proc 6843:io.va.exposed:p0/u0a68 for activity io.va.exposed/com.lody.virtual.client.stub.StubActivity$C0
```

**Comment by Enyby** [comment] 2019-12-22 09:38
There is no `armeabi` folder in apk.
There are `armeabi-v7a` and `x86`.
Since this is an x86 emulator, I think about the `x86` folder, since there is a `libepic.so` file in the `armeabi-v7a` folder.
Then this is duplicate of #746.

**Comment by ghost** [comment] 2019-12-24 11:31
I saw that issue, it may work on some emulators but doesn't work on Bluestacks and Memu so I opened the issue
It's obvious that Bluestacks or VX is looking for non-existing lib

**Comment by Enyby** [comment] 2019-12-24 14:38
You need wait new release.
Or you can download https://bintray.com/twsxtd/maven/download_file?file_path=me%2Fweishu%2Fepic%2F0.8.1-c%2Fepic-0.8.1-c.aar
open in 7-zip, extract `jni/x86/libepic.so` and put in appropriate place in the emulator and set proper right to it.

**Comment by ghost** [comment] 2019-12-26 17:35
All right but nevermind, I realized I can create multiple instances on BS

**Closed as completed** 2020-11-24 12:56 UTC
Labels: fixed
